# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xai < Formula
  desc ""
  homepage "https://github.com/11301858/XAISuite"
  version "2.0.5"

  on_macos do
    url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.5/xaisuitecli_2.0.5_darwin_all.tar.gz"
    sha256 "7b4af8281ac0a635c890d1dcd79704d0ec987a926bf035ec7784bf44c5bceb68"

    def install
      bin.install "xaisuitecli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.5/xaisuitecli_2.0.5_linux_amd64.tar.gz"
      sha256 "a8e0c4d593ca2a4534332d938d767d4ebc3f0e4fdd638e0982af878dde9b5846"

      def install
        bin.install "xai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.5/xaisuitecli_2.0.5_linux_arm64.tar.gz"
      sha256 "5f47234f6083d2682f3ab984873690b62f124feb0804faa795f69179b0931833"

      def install
        bin.install "xai"
      end
    end
  end
end
