# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xai < Formula
  desc ""
  homepage "https://github.com/11301858/XAISuite"
  version "2.0.7"

  on_macos do
    url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.7/xaisuitecli_2.0.7_darwin_all.tar.gz"
    sha256 "2b039236a9fd83423890c003fc5c503c8861c1fa995c63d41b8abcd80c1c1ddb"

    def install
      bin.install "xaisuitecli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.7/xaisuitecli_2.0.7_linux_arm64.tar.gz"
      sha256 "20467d22e77a04f734b724b0320bd3893f08252e536b0d51ebb8a40c5ad14a92"

      def install
        bin.install "xai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.7/xaisuitecli_2.0.7_linux_amd64.tar.gz"
      sha256 "b4a7e655a57af592fa8532966a5d1e7e110ce24cbcabb0f9d533daec495a258b"

      def install
        bin.install "xai"
      end
    end
  end
end
