# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xai < Formula
  desc ""
  homepage "https://github.com/11301858/XAISuite"
  version "2.0.4"

  on_macos do
    url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.4/xaisuitecli_2.0.4_darwin_all.tar.gz"
    sha256 "07201d81cb5652bc363a11b64ba425bedfc84abefc440cc6af4698cfa9b16240"

    def install
      bin.install "xaisuitecli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.4/xaisuitecli_2.0.4_linux_arm64.tar.gz"
      sha256 "003b6240bdcf3fec6c3e2ae96a28f7e43bac01e80283a85d2015d19d20c323e6"

      def install
        bin.install "xai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/11301858/xaisuitecli/releases/download/v2.0.4/xaisuitecli_2.0.4_linux_amd64.tar.gz"
      sha256 "4b1e52147c733b568e84f46747c1fc84dd846cad775817b6e7a16a74c073fe7f"

      def install
        bin.install "xai"
      end
    end
  end
end
